CC = gcc
PYTHON = python3
CFLAGS = -g -Wall -I runtime -I runtime/include
export ZEN_PATH = $(shell pwd):$(shell pwd)/src
BOOTSTRAP_DIR = bootstrap
SRC_DIR = src
BUILD_DIR = build
BIN_DIR = bin
RUNTIME_DIR = runtime

ZEN_SRC = $(SRC_DIR)/zen.zl
ZEN_DRIVER_C = $(BUILD_DIR)/zen.c
ZEN_EXE = $(BIN_DIR)/zen

STUBS_C = $(BUILD_DIR)/compiler_stubs.c
RUNTIME_C = $(RUNTIME_DIR)/main_wrapper.c \
               $(RUNTIME_DIR)/io/io_default.c \
               $(RUNTIME_DIR)/object/string.c \
               $(RUNTIME_DIR)/object/list.c \
               $(RUNTIME_DIR)/sys/sys_default.c \
               $(RUNTIME_DIR)/memory/allocator_default.c
# Components generated by bootstrap
COMPONENTS_C = $(BUILD_DIR)/Token.c $(BUILD_DIR)/Lexer.c $(BUILD_DIR)/AST.c $(BUILD_DIR)/Parser.c $(BUILD_DIR)/CTranspiler.c $(BUILD_DIR)/Resolver.c $(BUILD_DIR)/DependencyGraph.c
COMPONENTS_H = $(BUILD_DIR)/Token.h $(BUILD_DIR)/Lexer.h $(BUILD_DIR)/AST.h $(BUILD_DIR)/Parser.h $(BUILD_DIR)/CTranspiler.h $(BUILD_DIR)/Resolver.h $(BUILD_DIR)/DependencyGraph.h

all: $(ZEN_EXE)

$(BIN_DIR)/zen: $(ZEN_DRIVER_C) $(COMPONENTS_C) $(COMPONENTS_H) $(RUNTIME_C)
	@mkdir -p $(BIN_DIR)
	$(CC) $(CFLAGS) -o $@ $(ZEN_DRIVER_C) $(COMPONENTS_C) $(RUNTIME_C) -I $(BUILD_DIR) -I $(RUNTIME_DIR)/sys -I $(RUNTIME_DIR)/io -I $(RUNTIME_DIR)/object -I $(RUNTIME_DIR)/memory

$(ZEN_DRIVER_C): $(ZEN_SRC)
	@mkdir -p $(BUILD_DIR)
	cd $(BOOTSTRAP_DIR) && $(PYTHON) Zen.py ../$(ZEN_SRC) ../$(ZEN_DRIVER_C)



$(BUILD_DIR)/Token.c: src/compiler/Token.zl $(ZEN_SRC)
	python3 bootstrap/Zen.py src/zen.zl src/compiler/Token.zl $@

$(BUILD_DIR)/Lexer.c: src/compiler/Lexer.zl $(ZEN_SRC)
	python3 bootstrap/Zen.py src/zen.zl src/compiler/Lexer.zl $@

$(BUILD_DIR)/AST.c: src/compiler/AST.zl $(ZEN_SRC)
	python3 bootstrap/Zen.py src/zen.zl src/compiler/AST.zl $@

$(BUILD_DIR)/Parser.c: src/compiler/Parser.zl $(ZEN_SRC)
	python3 bootstrap/Zen.py src/zen.zl src/compiler/Parser.zl $@

$(BUILD_DIR)/CTranspiler.c: src/compiler/CTranspiler.zl $(ZEN_SRC)
	python3 bootstrap/Zen.py src/zen.zl src/compiler/CTranspiler.zl $@

$(BUILD_DIR)/Resolver.c: src/compiler/Module/Resolver.zl $(ZEN_SRC)
	python3 bootstrap/Zen.py src/zen.zl src/compiler/Module/Resolver.zl $@

$(BUILD_DIR)/DependencyGraph.c: src/compiler/Module/DependencyGraph.zl $(ZEN_SRC)
	python3 bootstrap/Zen.py src/zen.zl src/compiler/Module/DependencyGraph.zl $@

$(STUBS_C):
	@mkdir -p $(BUILD_DIR)
	@echo "Copying stubs..."
	cp src/stubs/*.h $(BUILD_DIR)/
	cp src/stubs/*.c $(BUILD_DIR)/
	
clean:
	rm -rf $(BUILD_DIR)/* $(BIN_DIR)/*

.PHONY: all clean
