#!/usr/bin/env bash
# Prepare editors/tree-sitter-zen + editors/zed for local Zed Install Dev Extension.
#
# Zed requires grammars to be fetched as a *git revision*. A bare directory with
# rev = "local" fails with: "failed to fetch revision local".
# This script:
#   1) generates the Tree-sitter parser
#   2) maintains a nested git repo inside editors/tree-sitter-zen with a real SHA
#   3) writes editors/zed/extension.toml with file:// + that SHA
#   4) syncs query files into editors/zed/languages/zen/
set -euo pipefail

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
GRAMMAR="$ROOT/editors/tree-sitter-zen"
ZED="$ROOT/editors/zed"
EXT_TOML="$ZED/extension.toml"

echo "=== Zenlang Zed setup ==="
echo "ROOT=$ROOT"

if ! command -v npm >/dev/null 2>&1; then
  echo "npm is required to generate the Tree-sitter grammar" >&2
  exit 1
fi
if ! command -v git >/dev/null 2>&1; then
  echo "git is required (Zed checkouts grammar by revision)" >&2
  exit 1
fi

echo "--- generate tree-sitter parser ---"
cd "$GRAMMAR"
if [[ ! -d node_modules ]]; then
  npm install --no-fund --no-audit
fi
npx tree-sitter generate

# Drop accidental native build artifacts from nested grammar repo
rm -f zen.so "*.wasm" 2>/dev/null || true

echo "--- nested git repo for Zed grammar rev ---"
# Nested repo is intentional and local-only (parent monorepo may ignore it).
if [[ ! -d .git ]]; then
  git init -q
  git config user.email "zenlang@local"
  git config user.name "Zenlang"
fi
if [[ ! -f .gitignore ]]; then
  printf 'node_modules/\n*.so\n*.wasm\npackage-lock.json\n' > .gitignore
fi

git add -A grammar.js package.json tree-sitter.json README.md queries src .gitignore 2>/dev/null || true
# Commit only when something changed
if ! git diff --cached --quiet 2>/dev/null || [[ -z "$(git rev-parse --verify HEAD 2>/dev/null || true)" ]]; then
  if git diff --cached --quiet 2>/dev/null && git rev-parse --verify HEAD >/dev/null 2>&1; then
    :
  else
    git commit -q -m "tree-sitter-zen grammar for Zed $(date -Iseconds)" || {
      # empty commit guard
      if [[ -z "$(git rev-parse --verify HEAD 2>/dev/null || true)" ]]; then
        git commit -q --allow-empty -m "tree-sitter-zen grammar for Zed"
      fi
    }
  fi
fi
# If there are staged changes, commit them
if ! git diff --cached --quiet 2>/dev/null; then
  git commit -q -m "tree-sitter-zen grammar for Zed $(date -Iseconds)"
fi
# If working tree has unstaged changes to tracked files, amend/add commit
if [[ -n "$(git status --porcelain grammar.js package.json tree-sitter.json README.md queries src 2>/dev/null)" ]]; then
  git add grammar.js package.json tree-sitter.json README.md queries src .gitignore
  git commit -q -m "tree-sitter-zen grammar for Zed $(date -Iseconds)" || true
fi

REV="$(git rev-parse HEAD)"
ABS_URL="file://${GRAMMAR}"
echo "  repository = ${ABS_URL}"
echo "  rev        = ${REV}"

# Sync queries into Zed language dir
mkdir -p "$ZED/languages/zen"
cp -f "$GRAMMAR/queries/"*.scm "$ZED/languages/zen/"

echo "--- write extension.toml ---"
cat > "$EXT_TOML" <<EOF
id = "zenlang"
name = "Zenlang"
version = "0.1.0"
schema_version = 1
authors = ["Zenlang contributors"]
description = "Zenlang language support — syntax highlighting, outline, and brackets for .zl / .zs"
repository = "https://github.com/zenlang/zen"

# Generated by scripts/setup_zed_extension.sh — do not use rev = "local"
[grammars.zen]
repository = "${ABS_URL}"
rev = "${REV}"
EOF

# Clear failed checkout caches for a clean reinstall
rm -rf "$ZED/grammars" 2>/dev/null || true

echo ""
echo "Done. In Zed:"
echo "  1. Extensions → uninstall any previous Zenlang dev extension (if listed)"
echo "  2. Install Dev Extension… → select:"
echo "       $ZED"
echo "  3. Open examples/getting_started/01_hello.zl"
echo ""
echo "If it still fails, check: zed: open log  (search for 'grammar zen')"
